Update backend.yml

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -72,6 +72,21 @@ jobs:
         -d "{\"rules\": $updated_rules}")
         echo "$response"
         echo "$response" | grep "HTTP/2 204" || exit 1
+    
+    - name: Verify trusted source
+      env:
+        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
+      run: |
+        for i in {1..10}; do
+          response=$(curl -s -X GET "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
+          -H "Content-Type: application/json" \
+          -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN")
+          echo "$response" | jq '.rules[] | select(.sources[] == "${{ steps.runner-ip.outputs.ip }}")' | grep -q "${{ steps.runner-ip.outputs.ip }}" && echo "Trusted source verified" && exit 0
+          echo "Trusted source not found. Retrying in 10 seconds..."
+          sleep 10
+        done
+        echo "Trusted source verification failed. Exiting..."
+        exit 1
 
     - name: Run tests
       env:
